<?php
if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Shortcode: [ttp_dash_notifications]
 * Aggregates alerts from BuddyPress, Better Messages, and Custom Systems.
 */
add_shortcode('ttp_dash_notifications', function() {
    if (!is_user_logged_in()) return '';

    $user_id = get_current_user_id();
    $notifications = [];

    // 1. Better Messages Alerts
    if (class_exists('Better_Messages')) {
        $unread_msg_count = Better_Messages()->functions->get_unread_messages_count($user_id);
        if ($unread_msg_count > 0) {
            $notifications[] = [
                'type' => 'message',
                'icon' => '💬',
                'title' => 'Unread Messages',
                'desc' => sprintf('You have %d unread private message(s).', $unread_msg_count),
                'link' => site_url('/messages/'),
                'link_text' => 'Open Inbox'
            ];
        }
    }

    // 2. BuddyPress Alerts (Forums, Groups, Announcements)
    if (function_exists('bp_notifications_get_notifications_for_user')) {
        // bp_notifications_get_notifications_for_user returns an array of HTML strings OR objects depending on format
        // We'll request 'object' format to parse it cleanly.
        $bp_alerts = bp_notifications_get_notifications_for_user($user_id, 'object');
        if (!empty($bp_alerts)) {
            foreach ($bp_alerts as $alert) {
                // Determine icon based on component
                $icon = '🔔';
                if ($alert->component_name == 'groups') $icon = '👥';
                if ($alert->component_name == 'bbpress') $icon = '🗣️';
                
                // Get the action link and text
                // BP has a filter 'bp_get_the_notification_description' but since we requested objects,
                // we'll need to parse it or just use the generic object data. 
                // A safer way is requesting string format and parsing the href, but let's use the object.
                // Wait, if we just request 'string', it returns fully formed HTML links. Let's do that for simplicity and wrap it.
            }
        }
        
        // Let's actually just get the 'string' array for BP notifications, it's safer for compatibility.
        $bp_strings = bp_notifications_get_notifications_for_user($user_id, 'string');
        if (!empty($bp_strings)) {
            foreach ($bp_strings as $bp_html) {
                $notifications[] = [
                    'type' => 'community',
                    'icon' => '🔔',
                    'title' => 'Community Alert',
                    'desc' => $bp_html, // This is an HTML <a> tag generated by BuddyPress
                    'link' => '',
                    'link_text' => ''
                ];
            }
        }
    }

    // 3. System Alerts (Certificate Ready)
    // Check if certificate condition is met but they haven't generated the hash yet
    // Or if they have a hash, remind them they can download it.
    // For performance, we'll quickly check if they have a hash for the Fundamentals course.
    $fundamentals_course = get_page_by_title("Placeholder Course: Fundamentals of Education", OBJECT, 'courses');
    if ($fundamentals_course) {
        $course_id = $fundamentals_course->ID;
        $hash = get_user_meta($user_id, '_ttp_cert_hash_' . $course_id, true);
        
        if ($hash) {
            // Check if we should still notify them. We could set a meta flag '_ttp_cert_notified'.
            $notified = get_user_meta($user_id, '_ttp_cert_notified_' . $course_id, true);
            if (!$notified) {
                $notifications[] = [
                    'type' => 'system',
                    'icon' => '🎓',
                    'title' => 'Certificate Unlocked!',
                    'desc' => 'Congratulations! Your official certificate is ready.',
                    'link' => site_url('/certificate/?course=' . $course_id . '&user=' . $user_id),
                    'link_text' => 'View Certificate',
                    'action_id' => 'dismiss_cert_alert_' . $course_id
                ];
            }
        }
    }

    ob_start();
    ?>
    <div class="ttp-card ttp-notifications-widget" style="padding: 24px; background: white; border-radius: 8px; border: 1px solid var(--ttp-border-light);">
        <h3 style="margin-top: 0; color: var(--ttp-text-head-light); border-bottom: 2px solid var(--ttp-primary); display: inline-block; padding-bottom: 8px;">Global Notifications</h3>
        
        <div style="margin-top: 16px;">
            <?php if (empty($notifications)) : ?>
                <div style="padding: 16px; background: #f8fafc; border-radius: 8px; text-align: center; color: var(--ttp-text-body-light);">
                    You're all caught up! No new notifications.
                </div>
            <?php else : ?>
                <?php foreach ($notifications as $alert) : ?>
                    <div style="display: flex; gap: 16px; padding: 16px; border: 1px solid var(--ttp-border-light); border-radius: 8px; margin-bottom: 12px; align-items: center; background: <?php echo ($alert['type'] == 'message') ? '#eff6ff' : (($alert['type'] == 'system') ? '#f0fdf4' : 'white'); ?>;">
                        <div style="font-size: 2rem;">
                            <?php echo $alert['icon']; ?>
                        </div>
                        <div style="flex: 1;">
                            <h4 style="margin: 0 0 4px 0; color: var(--ttp-text-head-light);"><?php echo esc_html($alert['title']); ?></h4>
                            <div style="font-size: 0.95rem; color: var(--ttp-text-body-light); margin: 0;">
                                <?php echo $alert['desc']; // Deliberately NOT escaped here because BP returns safe HTML ?>
                            </div>
                        </div>
                        <?php if (!empty($alert['link'])) : ?>
                            <div>
                                <a href="<?php echo esc_url($alert['link']); ?>" class="ttp-btn-secondary" style="display: inline-block; background: white; color: var(--ttp-primary); border: 1px solid var(--ttp-primary); padding: 8px 16px; text-decoration: none; border-radius: 4px; font-weight: 600; font-size: 0.875rem;"><?php echo esc_html($alert['link_text']); ?></a>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
    <?php
    return ob_get_clean();
});
?>
